name: programmers_badge_action

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    types: [ trigger-workflow ]
  workflow_dispatch: # 직접 실행 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    # 권한 명시 (Settings에서 설정하는 것과 같은 효과)
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Java program
        env:
          # 시크릿에서 가져온 아이디/비번
          PROGRAMMERS_TOKEN_ID: ${{ secrets.PROGRAMMERS_TOKEN_ID }}
          PROGRAMMERS_TOKEN_PW: ${{ secrets.PROGRAMMERS_TOKEN_PW }}
        run: ./gradlew run

      - name: Commit and Push changes
        env:
          # 별도의 GH_PAT 없이 기본 토큰으로 푸시하도록 설정
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_NAME: ${{ secrets.GIT_NAME }}
        run: |
          git config --global user.email "${GIT_EMAIL}"
          git config --global user.name "${GIT_NAME}"
          git add .
          
          # 변경사항이 있는지 확인 후 커밋/푸시
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update badge"
            git push
          else
            echo "No changes to commit"
          fi
